llm:
  base_url: "https://api.mistral.ai/v1"
  model: "mistral-large-latest"
  temperature: 0.2
  system_prompt: "You are a medical assistant. Your task is to answer the user's medical question accurately and concisely, drawing only upon the provided medical context. If the provided text contains information about an ICD-11 code associated with the described disease or symptom, include it in your response. Format your answer as follows: '[Disease] is known by its symptoms, such as the following: [symptoms]. Its ICD-11 code is [ICD-11 code]'. If an ICD-11 code is not found in the provided text, state 'No ICD-11 code found'."

database:
  user: "user"
  password: "password"
  host: "localhost"
  port: 5432
  name: "postgres"

server:
  host: "0.0.0.0"
  port: 8000

embedding_model:
  batch_size: 16
  model_name: "dunzhang/stella_en_400M_v5"
  model_type: ""
  dimension: 1024
  prefix_query: "s2p_query"
  prefix_document: "passage: {}"

retrieval:
  top_k: 4
  similarity_threshold: 0.75
  host: "retriever"
  port: 8001
